package com.example.util

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.net.Uri
import androidx.core.content.FileProvider
import com.example.data.model.CustomerFileEntity
import com.example.data.model.UserEntity
import java.io.File
import java.io.FileOutputStream

object PdfReportGenerator {
  fun generatePdfReport(
    context: Context,
    files: List<CustomerFileEntity>,
    currentUser: UserEntity,
    periodLabel: String,
    customAppName: String
  ): File {
    val document = PdfDocument()
    val pageWidth = 595
    val pageHeight = 842
    val pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, 1).create()
    val page = document.startPage(pageInfo)
    val canvas: Canvas = page.canvas
    val textPaint = Paint().apply {
      isAntiAlias = true
      textSize = 10f
      color = Color.DKGRAY
    }
    val headerPaint = Paint().apply {
      isAntiAlias = true
      textSize = 16f
      typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
      color = Color.rgb(10, 25, 47)
    }
    val subHeaderPaint = Paint().apply {
      isAntiAlias = true
      textSize = 10f
      typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
      color = Color.rgb(30, 58, 138)
    }
    val tableHeaderPaint = Paint().apply {
      isAntiAlias = true
      textSize = 9f
      typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
      color = Color.WHITE
    }
    val bgHeaderPaint = Paint().apply {
      color = Color.rgb(10, 25, 47)
    }
    val alternateRowPaint = Paint().apply {
      color = Color.rgb(245, 247, 250)
    }
    val borderPaint = Paint().apply {
      color = Color.LTGRAY
      strokeWidth = 0.5f
      style = Paint.Style.STROKE
    }
    var y = 40f

    canvas.drawText(customAppName.ifBlank { "RM File Management Suite" }, 30f, y, headerPaint)
    y += 18f
    canvas.drawText("EXECUTIVE PERFORMANCE SUMMARY REPORT", 30f, y, subHeaderPaint)
    y += 14f
    textPaint.textSize = 8.5f
    val generatedTime = DateUtils.formatDateTime(DateUtils.currentDhakaMillis())
    canvas.drawText("Generated by: ${currentUser.name} (${currentUser.role} ${currentUser.rmCode}) | Timezone: Asia/Dhaka (GMT+6)", 30f, y, textPaint)
    y += 12f
    canvas.drawText("Reporting Period: $periodLabel | Generated at: $generatedTime", 30f, y, textPaint)
    y += 16f

    val totalCount = files.size
    val approvedCount = files.count { it.applicationStatus.equals("Approved", true) }
    val submittedCount = files.count { it.applicationStatus.equals("Submitted", true) }
    val collectedCount = files.count { it.applicationStatus.equals("Collected", true) }
    val declinedCount = files.count { it.applicationStatus.equals("Declined", true) }
    val kpiBoxPaint = Paint().apply {
      color = Color.rgb(240, 244, 248)
    }
    canvas.drawRect(30f, y, pageWidth - 30f, y + 42f, kpiBoxPaint)
    canvas.drawRect(30f, y, pageWidth - 30f, y + 42f, borderPaint)

    val kpiTextPaint = Paint().apply {
      isAntiAlias = true
      textSize = 9f
      typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
      color = Color.rgb(15, 23, 42)
    }
    canvas.drawText("TOTAL FILES: $totalCount", 45f, y + 16f, kpiTextPaint)
    canvas.drawText("APPROVED: $approvedCount", 160f, y + 16f, kpiTextPaint)
    canvas.drawText("SUBMITTED: $submittedCount", 270f, y + 16f, kpiTextPaint)
    canvas.drawText("COLLECTED: $collectedCount", 380f, y + 16f, kpiTextPaint)
    canvas.drawText("DECLINED: $declinedCount", 490f, y + 16f, kpiTextPaint)

    val approvalRatio = if (totalCount > 0) (approvedCount * 100 / totalCount) else 0
    val kpiSubText = Paint().apply {
      isAntiAlias = true
      textSize = 7.5f
      color = Color.GRAY
    }
    canvas.drawText("Overall Approval Conversion Rate: $approvalRatio% | Confidential Internal Banking Records", 45f, y + 32f, kpiSubText)
    y += 56f

    val colX = floatArrayOf(30f, 100f, 210f, 290f, 370f, 435f, 480f, pageWidth - 30f)
    canvas.drawRect(30f, y, pageWidth - 30f, y + 18f, bgHeaderPaint)
    canvas.drawText("CC-Number", colX[0] + 4f, y + 12f, tableHeaderPaint)
    canvas.drawText("Customer Name", colX[1] + 4f, y + 12f, tableHeaderPaint)
    canvas.drawText("Mobile", colX[2] + 4f, y + 12f, tableHeaderPaint)
    canvas.drawText("Product", colX[3] + 4f, y + 12f, tableHeaderPaint)
    canvas.drawText("Status", colX[4] + 4f, y + 12f, tableHeaderPaint)
    canvas.drawText("RM", colX[5] + 4f, y + 12f, tableHeaderPaint)
    canvas.drawText("Date", colX[6] + 4f, y + 12f, tableHeaderPaint)
    y += 18f

    val rowPaint = Paint().apply {
      isAntiAlias = true
      textSize = 8f
      color = Color.BLACK
    }
    var rowIndex = 0
    for (f in files.take(35)) {
      if (rowIndex % 2 == 1) {
        canvas.drawRect(30f, y, pageWidth - 30f, y + 16f, alternateRowPaint)
      }
      canvas.drawLine(30f, y + 16f, pageWidth - 30f, y + 16f, borderPaint)
      val ccText = f.ccNumber.ifBlank { f.fileId }
      canvas.drawText(ccText.take(12), colX[0] + 4f, y + 11f, rowPaint)
      canvas.drawText(f.customerName.take(18), colX[1] + 4f, y + 11f, rowPaint)
      canvas.drawText(f.mobile.take(13), colX[2] + 4f, y + 11f, rowPaint)
      canvas.drawText(f.productType.take(12), colX[3] + 4f, y + 11f, rowPaint)

      val statusPaint = Paint(rowPaint).apply {
        typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        color = when (f.applicationStatus) {
          "Approved" -> Color.rgb(21, 128, 61)
          "Submitted" -> Color.rgb(29, 78, 216)
          "Declined" -> Color.rgb(185, 28, 28)
          else -> Color.DKGRAY
        }
      }
      canvas.drawText(f.applicationStatus.take(10), colX[4] + 4f, y + 11f, statusPaint)
      canvas.drawText(f.assignedRmCode.take(6), colX[5] + 4f, y + 11f, rowPaint)
      canvas.drawText(DateUtils.formatDateOnly(f.updatedAt), colX[6] + 4f, y + 11f, rowPaint)
      y += 16f
      rowIndex++
    }

    y = pageHeight - 30f
    val footerPaint = Paint().apply {
      isAntiAlias = true
      textSize = 7.5f
      color = Color.GRAY
    }
    canvas.drawText("CONFIDENTIAL DOCUMENT | STRICTLY FOR INTERNAL BANKING USE | NOT FOR PUBLIC DISSEMINATION", 30f, y, footerPaint)
    canvas.drawText("Page 1 of 1", pageWidth - 80f, y, footerPaint)
    document.finishPage(page)

    val reportsDir = File(context.cacheDir, "reports").apply { mkdirs() }
    val reportFile = File(reportsDir, "RM_Report_${System.currentTimeMillis()}.pdf")
    FileOutputStream(reportFile).use { out ->
      document.writeTo(out)
    }
    document.close()
    return reportFile
  }

  fun shareOrViewPdf(context: Context, pdfFile: File) {
    val uri: Uri = try {
      FileProvider.getUriForFile(
        context,
        "${context.packageName}.fileprovider",
        pdfFile
      )
    } catch (e: Exception) {
      Uri.fromFile(pdfFile)
    }
    val intent = Intent(Intent.ACTION_SEND).apply {
      type = "application/pdf"
      putExtra(Intent.EXTRA_STREAM, uri)
      putExtra(Intent.EXTRA_SUBJECT, "Performance Summary Report (PDF)")
      addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
    }
    context.startActivity(Intent.createChooser(intent, "Open or Share PDF Report"))
  }

  fun generateAndSharePdfReport(
    context: Context,
    files: List<CustomerFileEntity>,
    currentUser: UserEntity? = null,
    timeFilterName: String = "All Time",
    generatedBy: String = "Bank Operations",
    customAppName: String = "RM File Management Suite"
  ): Boolean {
    return try {
      val user = currentUser ?: UserEntity(
        rmCode = "ADMIN",
        name = generatedBy,
        role = "ADMIN"
      )
      val file = generatePdfReport(context, files, user, timeFilterName, customAppName)
      shareOrViewPdf(context, file)
      true
    } catch (e: Exception) {
      false
    }
  }
}
